package com.tien.aivirabackend.constant;

public enum OrderStatus {
    PENDING_PAYMENT, PAID, PENDING_CONFIRMATION, CONFIRMED, PACKING, SHIPPING, COMPLETED, CANCELLED, PAYMENT_FAILED,
    EXPIRED, REFUNDED
}
